### ISSUE TITLE
Can I automatically log out after logging out of the authentication center first?

### ISSUE THREAD

**Issue by liquehuo** [sajanv88/AbpVue#29]
Excuse me ：
Can I automatically log out after logging out of the authentication center first?

**Comment by sajanv88** [comment]
If I understand your question correctly: 

Yes, it is possible. When you logout from the auth server try to invalidate the token provided to the UI. Within 30 seconds you will see a popup on your screen.

**Comment by sajanv88** [comment]
You have to invalidate the token in the backend.  UI will show this popup automatically. 

![Screenshot 2024-02-28 at 10 25 26](https://github.com/sajanv88/AbpVue/assets/40479827/d21bf767-675d-4cef-b213-9f838351d842)

**Comment by liquehuo** [comment]
oh thanks, i got your mean！
but now, when i logout from the auth server , whether the token invalid？ i want know

**Comment by sajanv88** [comment]
No. If you are using openiddict module in your Abp application then you should be able to use the method to revoke your token.  https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs#L1165

Refer to the openiddict/abp docs for more information.
