### ISSUE TITLE
Importing from server is not allowed in the Vue part of your app. [importing ../../..//server/api/abpServiceProxy/[...].ts from index.html]

### ISSUE THREAD

**Issue by Peregrine1** [sajanv88/AbpVue#35]
I configured the project according to the author's documentation and this error was thrown when I started it. I suspected that it was a problem with the nuxt version, but the problem still exists after trying to switch versions.If anyone has encountered a similar problem, please give me an answer. Thanks.
local nuxt version:3.11.1

**Comment by sajanv88** [comment]
You must use `getAbpServiceProxy` method.  For reference take a look at this https://github.com/sajanv88/AbpVue/blob/main/store/tenantStore.ts#L59C22-L59C40

**Comment by Peregrine1** [comment]
Thank you so much for your help, I think I've found the problem!

**Comment by sajanv88** [comment]
@Peregrine1 glad you found it. FYI:  I am going to remove all the abp proxy from the repo in the next release.

**Comment by Peregrine1** [comment]
I wonder if this advice is appropriate if you could consider uploading the backend code to github as well, which may help beginners get started faster.

**Comment by sajanv88** [comment]
I think you are referring to the abp code. 

Here is the abp code: https://github.com/sajanv88/Abp-single-layer-demo  It is just a boilerplate that I have hosted in my server. You can read more about abp single layer application here: https://docs.abp.io/en/abp/latest/Getting-Started-Single-Layered?UI=MVC&DB=EF

**Comment by Peregrine1** [comment]
> I think you are referring to the abp code.
> 
> Here is the abp code: https://github.com/sajanv88/Abp-single-layer-demo It is just a boilerplate that I have hosted in my server. You can read more about abp single layer application here: https://docs.abp.io/en/abp/latest/Getting-Started-Single-Layered?UI=MVC&DB=EF

Yes, thank you
